@url=http://localhost:8080
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsImlhdCI6MTY4MzMxNDA4NywiZXhwIjoxNjgzNDAwNDg3fQ.bS0nMRBsEtWEb0kHZ59LL1rz-MPquMqFOn1UFV-261Y

GET {{url}}/api/v1/impresa
Authorization: Bearer {{token}}